### ISSUE TITLE
Uncaught TypeError: Cannot read property 'segments' of undefined

### ISSUE THREAD

**Issue by idealhack** [videojs/videojs-contrib-hls#1124]
## Description

JSBin link: http://jsbin.com/fotagevuvu/edit?html,output

The HLS source were able to be played on Safari and VLC.

## Sources

http://files.tusdk.com/tmp/videojs-contrib-hls-test/play.m3u8

Note: I test with a CORS server on my local network, but the link below does not has CORS headers.

### Expected

The video should begin to playback.

### Error output

```
Uncaught TypeError: Cannot read property 'segments' of undefined
    at https://unpkg.com/videojs-contrib-hls@5.5.3/dist/videojs-contrib-hls.js:18036:25
    at Array.reduce (native)
    at VirtualSourceBuffer.processPendingSegments_ (https://unpkg.com/videojs-contrib-hls@5.5.3/dist/videojs-contrib-hls.js:18031:45)
    at VirtualSourceBuffer.done_ (https://unpkg.com/videojs-contrib-hls@5.5.3/dist/videojs-contrib-hls.js:17848:12)
    at Worker.VirtualSourceBuffer.transmuxer_.onmessage (https://unpkg.com/videojs-contrib-hls@5.5.3/dist/videojs-contrib-hls.js:17673:22)
```

## Additional Information

`npm test` also failed

### videojs-contrib-hls version

videojs-contrib-hls 5.5.3

### videojs version

video.js 5.19.2

### Browsers

* Chrome 58.0.3029
* Firefox 49.0.0

### Platforms

* macOS 10.12.0

**Comment by idealhack** [comment]
Never mind, I just realized the video format are not supported by Chrome.
