### ISSUE TITLE
videojs-contrib-hls.js:15696 Uncaught TypeError: Cannot read property 'segments' of undefined     at https://unpkg.com/videojs-contrib-hls@4.1.1/dist/videojs-contrib-hls.js:15696:25     at Array.reduce (native)     at VirtualSourceBuffer.processPendingSegments_ (https://unpkg.com/videojs-contrib-hls@4.1.1/dist/videojs-contrib-hls.js:15691:45)     at VirtualSourceBuffer.done_ (https://unpkg.com/videojs-contrib-hls@4.1.1/dist/videojs-contrib-hls.js:15538:12)     at Worker.VirtualSourceBuffer.transmuxer_.onmessage (https://unpkg.com/videojs-contrib-hls@4.1.1/dist/videojs-contrib-hls.js:15363:22)

### ISSUE THREAD

**Issue by Dolphy888** [videojs/videojs-contrib-hls#1168]
Hello,

I got an error can you tell me how fix it please 

error:

```
videojs-contrib-hls.js:15696 Uncaught TypeError: Cannot read property 'segments' of undefined
    at https://unpkg.com/videojs-contrib-hls@4.1.1/dist/videojs-contrib-hls.js:15696:25
    at Array.reduce (native)
    at VirtualSourceBuffer.processPendingSegments_ (https://unpkg.com/videojs-contrib-hls@4.1.1/dist/videojs-contrib-hls.js:15691:45)
    at VirtualSourceBuffer.done_ (https://unpkg.com/videojs-contrib-hls@4.1.1/dist/videojs-contrib-hls.js:15538:12)
    at Worker.VirtualSourceBuffer.transmuxer_.onmessage (https://unpkg.com/videojs-contrib-hls@4.1.1/dist/videojs-contrib-hls.js:15363:22)
```

Code:

```
<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8 />
<title>videojs-contrib-hls embed</title>
  
  <!--

  Uses the latest versions of video.js and videojs-contrib-hls.

  To use specific versions, please change the URLs to the form:-->

  <link href="https://unpkg.com/video.js@5.16.0/dist/video-js.css" rel="stylesheet">
  <script src="https://unpkg.com/video.js@5.16.0/dist/video.js"></script>
  <script src="https://unpkg.com/videojs-contrib-hls@4.1.1/dist/videojs-contrib-hls.js"></script>

 
  
</head>
<body>
  <h1>Video.js Example Embed</h1>

  <video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="268" 
  data-setup='{}'>
    <source src="https://www.gentech-digital.com/test2/demos/testfile.m3u8" type="application/x-mpegURL">
  </video>
  
  <script>
  </script>
  
</body>
</html>

```

**Comment by mjneil** [comment]
Your playlist is a fragmented MP4 stream, but you are missing the `EXT-X-MAP`. [Each segment must have an `EXT-X-MAP` tag applied to it](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-3.3)

**Comment by gesinger** [comment]
It also looks like the source is down now. @Dolphy888 , please give @mjneil 's suggestion a shot, and if you are still experiencing problems, please open a new issue with the example source in our [starter template](http://jsbin.com/vokipos/8/edit?html,output). Thank you.
