### ISSUE TITLE
Not working on Mac

### ISSUE THREAD

**Issue by shaharmor** [videojs/videojs-contrib-hls#360]
Hi,

When playing the demo page in Chrome version 44.0.2403.130 (64-bit) on OSX 10.10.4, i'm getting these errors in the console and the video isn't playing:
```javascript
videojs-media-sources.js:186 Uncaught TypeError: self.source.swfObj.CallFunction is not a function
video.dev.js:1457 VIDEOJS: Video.js: buffered unavailable on Hls playback technology element. TypeError: this.el_.vjs_getProperty is not a function
    at vjs.Flash.buffered (http://videojs.github.io/videojs-contrib-hls/node_modules/video.js/dist/video-js/video.dev.js:7953:42)
    at vjs.Player.techGet (http://videojs.github.io/videojs-contrib-hls/node_modules/video.js/dist/video-js/video.dev.js:4322:31)
    at vjs.Player.buffered (http://videojs.github.io/videojs-contrib-hls/node_modules/video.js/dist/video-js/video.dev.js:4474:23)
    at vjs.Player.bufferedPercent (http://videojs.github.io/videojs-contrib-hls/node_modules/video.js/dist/video-js/video.dev.js:4495:23)
    at vjs.Player.onProgress (http://videojs.github.io/videojs-contrib-hls/node_modules/video.js/dist/video-js/video.dev.js:4216:12)
    at HTMLDivElement.ret (http://videojs.github.io/videojs-contrib-hls/node_modules/video.js/dist/video-js/video.dev.js:885:15)
    at HTMLDivElement.data.dispatcher (http://videojs.github.io/videojs-contrib-hls/node_modules/video.js/dist/video-js/video.dev.js:360:29)
    at Function.vjs.trigger (http://videojs.github.io/videojs-contrib-hls/node_modules/video.js/dist/video-js/video.dev.js:605:25)
    at vjs.Component.trigger (http://videojs.github.io/videojs-contrib-hls/node_modules/video.js/dist/video-js/video.dev.js:2503:7)
    at XMLHttpRequest.<anonymous> (https://s3.amazonaws.com/github-cloud/releases/14029328/97ee1012-0e12-11e5-…IJMK3TQ&Expires=1438949564&Signature=RBbTM17zfBTwl54jP8fWFGA5duU%3D:3:8687)
video.dev.js:4336 Uncaught TypeError: this.el_.vjs_getProperty is not a function
```

**Comment by mmcc** [comment]
Ended up being an issue with OP's environment: videojs/video.js#2446
