### ISSUE TITLE
Uncaught TypeError: this.c.vjs_getProperty is not a function

### ISSUE THREAD

**Issue by himslm01** [videojs/videojs-contrib-hls#390]
Similar to issue https://github.com/videojs/videojs-contrib-hls/issues/222, when I dispose of a videojs player which was playing an HLS stream I receive the above exception.

I believe I am using the most up-to-date releases of the videojs components:
* videojs-contrib-hls v0.17.9
* videojs-contrib-media-sources v0.3.1
* videojs v4.12.15

I have a simple demonstration here:
https://github.com/himslm01/videojs_test2
 
The full console log from Chrome is:

    VIDEOJS: Video.js: currentSrc unavailable on Hls playback technology element. TypeError: this.c.vjs_getProperty is not a function
        at t.g.currentSrc (http://localhost:8180/videojs_test2/js/video.js/video-js-4.12.15/video.js:139:420)
        at M (http://localhost:8180/videojs_test2/js/video.js/video-js-4.12.15/video.js:68:160)
        at s.currentSrc (http://localhost:8180/videojs_test2/js/video.js/video-js-4.12.15/video.js:77:276)
        at videojs.Hls.fillBuffer (http://localhost:8180/videojs_test2/js/video.js/videojs-contrib-hls-0.17.9/videojs-hls.js:706:15)
        at videojs.Hls.checkBuffer_ (http://localhost:8180/videojs_test2/js/video.js/videojs-contrib-hls-0.17.9/videojs-hls.js:655:8)
        at e (http://localhost:8180/videojs_test2/js/video.js/video-js-4.12.15/video.js:14:285) video.js:139
    Uncaught TypeError: this.c.vjs_getProperty is not a function 

I also note that I have seen the disposed of player continue to pull both the .m3u8 and the media files referenced from it.

**Comment by dmlap** [comment]
I believe the underlying causes for this issue have been addressed in the 1.x releases. Please re-open if you're still seeing the issue after upgrading.
