### ISSUE TITLE
Can't install by npm?

### ISSUE THREAD

**Issue by hanfeisun** [videojs/videojs-contrib-hls#468]
When I install `videojs-contrib-hls` by `npm`, it throws ERROR. 

The reason is that the test folder doesn't exist in the NPM distribution

```
$ npm install --save-dev videojs-contrib-hls --verbose
npm info it worked if it ends with ok
npm verb cli [ 'node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--save-dev',
npm verb cli   'videojs-contrib-hls',
npm verb cli   '--verbose' ]
npm info using npm@2.11.3
npm info using node@v0.12.7
npm verb install initial load of /Users/hanfeisun/Workspace/waylens/package.json
npm WARN package.json harchi-video-player@0.0.1 No repository field.
npm WARN package.json harchi-video-player@0.0.1 No license field.
npm verb installManyTop reading scoped package data from /Users/hanfeisun/Workspace/waylens/node_modules/css-loader/package.json
npm verb installManyTop reading scoped package data from /Users/hanfeisun/Workspace/waylens/node_modules/extract-text-webpack-plugin/package.json
npm verb installManyTop reading scoped package data from /Users/hanfeisun/Workspace/waylens/node_modules/file-loader/package.json
npm verb installManyTop reading scoped package data from /Users/hanfeisun/Workspace/waylens/node_modules/imports-loader/package.json
npm verb installManyTop reading scoped package data from /Users/hanfeisun/Workspace/waylens/node_modules/json-loader/package.json
npm verb installManyTop reading scoped package data from /Users/hanfeisun/Workspace/waylens/node_modules/mapbox.js/package.json
npm verb installManyTop reading scoped package data from /Users/hanfeisun/Workspace/waylens/node_modules/raw-loader/package.json
npm verb installManyTop reading scoped package data from /Users/hanfeisun/Workspace/waylens/node_modules/spritesheet-js/package.json
npm verb installManyTop reading scoped package data from /Users/hanfeisun/Workspace/waylens/node_modules/style-loader/package.json
npm verb installManyTop reading scoped package data from /Users/hanfeisun/Workspace/waylens/node_modules/webpack/package.json
npm info package.json mapbox.js@2.2.2 No license field.
npm info package.json raw-loader@0.5.1 No license field.
npm verb readDependencies loading dependencies from /Users/hanfeisun/Workspace/waylens/package.json
npm verb cache add spec videojs-contrib-hls
npm verb addLocalDirectory /Users/hanfeisun/.npm/videojs-contrib-hls/1.2.2/package.tgz not in flight; packing
npm verb tar pack [ '/Users/hanfeisun/.npm/videojs-contrib-hls/1.2.2/package.tgz',
npm verb tar pack   '/Users/hanfeisun/Workspace/waylens/videojs-contrib-hls' ]
npm verb tarball /Users/hanfeisun/.npm/videojs-contrib-hls/1.2.2/package.tgz
npm verb folder /Users/hanfeisun/Workspace/waylens/videojs-contrib-hls
npm info prepublish videojs-contrib-hls@1.2.2
 
> videojs-contrib-hls@1.2.2 prepublish /Users/hanfeisun/Workspace/waylens/videojs-contrib-hls
> if [ -z "$TRAVIS" ]; then grunt; fi

Running "test" task

Running "jshint:gruntfile" (jshint) task
>> 1 file lint free.

Running "jshint:src" (jshint) task
>> 8 files lint free.

Running "jshint:test" (jshint) task
>> 12 files lint free.

Running "manifests-to-js" task

Running "connect:test" (connect) task
Started connect web server on http://:::9999

Running "karma:chrome" (karma) task
WARN: 'VIDEOJS:', 'WARN:', 'The Hls tech was added to the videojs object when it should be registered using videojs.registerTech(name, tech)'
WARN: 'VIDEOJS:', 'WARN:', 'HLS is no longer a tech. Please remove it from your player's techOrder.'
WARN: 'VIDEOJS:', 'WARN:', 'player.hls is deprecated. Use player.tech.hls instead.'
WARN: 'VIDEOJS:', 'WARN:', 'player.hls is deprecated. Use player.tech.hls instead.'
WARN: 'VIDEOJS:', 'WARN:', 'player.hls is deprecated. Use player.tech.hls instead.'
WARN: 'VIDEOJS:', 'WARN:', 'Problem encountered with the current HLS playlist. Switching to another playlist.'
WARN: 'VIDEOJS:', 'WARN:', 'player.hls is deprecated. Use player.tech.hls instead.'
WARN: 'VIDEOJS:', 'WARN:', 'Problem encountered with the current HLS playlist. Switching to another playlist.'
WARN: 'VIDEOJS:', 'WARN:', 'Problem encountered with the current HLS playlist. Switching to another playlist.'
WARN: 'VIDEOJS:', 'WARN:', 'Problem encountered with the current HLS playlist. Switching to another playlist.'
WARN: 'VIDEOJS:', 'WARN:', 'Problem encountered with the current HLS playlist. Switching to another playlist.'
WARN: 'VIDEOJS:', 'WARN:', 'Problem encountered with the current HLS playlist. Switching to another playlist.'
WARN: 'VIDEOJS:', 'WARN:', 'Problem encountered with the current HLS playlist. Switching to another playlist.'
WARN: 'VIDEOJS:', 'WARN:', 'Problem encountered with the current HLS playlist. Switching to another playlist.'
WARN: 'VIDEOJS:', 'WARN:', 'Problem encountered with the current HLS playlist. Switching to another playlist.'
WARN: 'VIDEOJS:', 'WARN:', 'Problem encountered with the current HLS playlist. No suitable alternatives found.'
WARN: 'VIDEOJS:', 'WARN:', 'The Hls component was added to the videojs object when it should be registered using videojs.registerComponent(name, component)'
WARN: 'VIDEOJS:', 'WARN:', 'The Hls component was added to the videojs object when it should be registered using videojs.registerComponent(name, component)'
WARN: 'VIDEOJS:', 'WARN:', 'HLS is no longer a tech. Please remove it from your player's techOrder.'
WARN: 'VIDEOJS:', 'WARN:', 'Problem encountered with the current HLS playlist. No suitable alternatives found.'
WARN: 'VIDEOJS:', 'WARN:', 'Problem encountered with the current HLS playlist. No suitable alternatives found.'
Chrome 47.0.2526 (Mac OS X 10.11.2): Executed 204 of 204 SUCCESS (2.548 secs / 2.077 secs)
/
Running "protractor:chrome" (protractor) task
webdriver-manager path: /Users/hanfeisun/Workspace/waylens/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager
Updating selenium standalone
downloading https://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.19/chromedriver_mac32.zip...
chromedriver_2.19.zip downloaded to /Users/hanfeisun/Workspace/waylens/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/selenium/chromedriver_2.19.zip
selenium-server-standalone-2.47.1.jar downloaded to /Users/hanfeisun/Workspace/waylens/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/selenium/selenium-server-standalone-2.47.1.jar
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
[launcher] Process exited with error code 1
/Users/hanfeisun/Workspace/waylens/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/nexttick.js:41
  goog.global.setTimeout(function() { throw exception; }, 0);
                                            ^
Error: Server terminated early with status 1
    at Error (native)
    at /Users/hanfeisun/Workspace/waylens/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/remote/index.js:204:25
    at promise.ControlFlow.runInFrame_ (/Users/hanfeisun/Workspace/waylens/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
    at goog.defineClass.notify (/Users/hanfeisun/Workspace/waylens/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)
    at promise.Promise.notify_ (/Users/hanfeisun/Workspace/waylens/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)
    at Array.forEach (native)
    at promise.Promise.notifyAll_ (/Users/hanfeisun/Workspace/waylens/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)
    at goog.async.run.processWorkQueue (/Users/hanfeisun/Workspace/waylens/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)
    at runMicrotasksCallback (node.js:337:7)
    at process._tickCallback (node.js:355:11)
>> /Users/hanfeisun/Workspace/waylens/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/nexttick.js:41
>>   goog.global.setTimeout(function() { throw exception; }, 0);
>>                                             ^
>> Error: Server terminated early with status 1
>>     at Error (native)
>>     at /Users/hanfeisun/Workspace/waylens/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/remote/index.js:204:25
>>     at promise.ControlFlow.runInFrame_ (/Users/hanfeisun/Workspace/waylens/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
>>     at goog.defineClass.notify (/Users/hanfeisun/Workspace/waylens/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)
>>     at promise.Promise.notify_ (/Users/hanfeisun/Workspace/waylens/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)
>>     at Array.forEach (native)
>>     at promise.Promise.notifyAll_ (/Users/hanfeisun/Workspace/waylens/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)
>>     at goog.async.run.processWorkQueue (/Users/hanfeisun/Workspace/waylens/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)
>>     at runMicrotasksCallback (node.js:337:7)
>>     at process._tickCallback (node.js:355:11)
Warning: Tests failed, protractor exited with code: 1 Use --force to continue.

Aborted due to warnings.
-
npm verb unsafe-perm in lifecycle true
npm info videojs-contrib-hls@1.2.2 Failed to exec prepublish script
npm ERR! addLocalDirectory Could not pack /Users/hanfeisun/Workspace/waylens/videojs-contrib-hls to /Users/hanfeisun/.npm/videojs-contrib-hls/1.2.2/package.tgz
npm ERR! addLocal Could not install /Users/hanfeisun/Workspace/waylens/videojs-contrib-hls
npm verb stack Error: videojs-contrib-hls@1.2.2 prepublish: `if [ -z "$TRAVIS" ]; then grunt; fi`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
npm verb stack     at EventEmitter.emit (events.js:110:17)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at ChildProcess.emit (events.js:110:17)
npm verb stack     at maybeClose (child_process.js:1015:16)
npm verb stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
npm verb pkgid videojs-contrib-hls@1.2.2
npm verb cwd /Users/hanfeisun/Workspace/waylens
npm ERR! Darwin 15.2.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save-dev" "videojs-contrib-hls" "--verbose"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! videojs-contrib-hls@1.2.2 prepublish: `if [ -z "$TRAVIS" ]; then grunt; fi`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the videojs-contrib-hls@1.2.2 prepublish script 'if [ -z "$TRAVIS" ]; then grunt; fi'.
npm ERR! This is most likely a problem with the videojs-contrib-hls package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     if [ -z "$TRAVIS" ]; then grunt; fi
npm ERR! You can get their info via:
npm ERR!     npm owner ls videojs-contrib-hls
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hanfeisun/Workspace/waylens/npm-debug.log
```

**Comment by gkatsev** [comment]
That's super weird. I'm pretty sure that prepublish isn't supposed to be run like that.

**Comment by gquinones** [comment]
Gary,

Check if the guy is running on a Mac, specifically with the El Capitan OS.
I've had similar problems and it turned out to be that I needed to update
Xcode and accept the licensing agreement. Super annoying and obscure issue,
especially since they point the finger of blame elsewhere.


https://github.com/phonegap/ios-deploy/issues/161





On Wed, Dec 9, 2015 at 9:59 AM, Gary Katsevman <notifications@github.com>
wrote:

> That's super weird. I'm pretty sure that prepublish isn't supposed to be
> run like that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/videojs/videojs-contrib-hls/issues/468#issuecomment-163281115>
> .
>



-- 
- Gerardo Quiñones

**Comment by hanfeisun** [comment]
@gquinones Yes, I'm using El Capitan OS.

When I use Git URL in `package.json`: 

```
  "devDependencies": {
    "videojs-contrib-hls": "git+https://github.com/videojs/videojs-contrib-hls#v1.2.2"
  }
```

Everything works well..

**Comment by gquinones** [comment]
When I upgraded my rig to El Capitan, everything broke for me. Even after I
updated Xcode, things were still broken. It wasn't until I opened Xcode and
went through the process of accepting the license agreement that npm
install started working correctly again. Totally different packages but
same tell-tale behavior of saying:

This is most likely a problem with the <your package here> package,

Glad you're back up and running.




On Wed, Dec 9, 2015 at 9:07 PM, Hanfei Sun <notifications@github.com> wrote:

> @gquinones <https://github.com/gquinones> Yes, I'm using El Capitan OS.
>
> When I use Git URL in package.json:
>
>   "devDependencies": {
>     "videojs-contrib-hls": "git+https://github.com/videojs/videojs-contrib-hls#v1.2.2"
>   }
>
> Everything works well..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/videojs/videojs-contrib-hls/issues/468#issuecomment-163463579>
> .
>



-- 
- Gerardo Quiñones

**Comment by forbesjo** [comment]
Closing since this has been resolved
