### ISSUE TITLE
protractor:chrome throws an error during test

### ISSUE THREAD

**Issue by hanfeisun** [videojs/videojs-contrib-hls#524]
Here is the log

```
Running "protractor:chrome" (protractor) task
webdriver-manager path: /Users/hanfeisun/Workspace/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager
selenium standalone is up to date.
chromedriver is up to date.
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
[launcher] Process exited with error code 1
/Users/hanfeisun/Workspace/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/nexttick.js:41
  goog.global.setTimeout(function() { throw exception; }, 0);
                                            ^
Error: Server terminated early with status 1
    at Error (native)
    at /Users/hanfeisun/Workspace/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/remote/index.js:204:25
    at promise.ControlFlow.runInFrame_ (/Users/hanfeisun/Workspace/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
    at goog.defineClass.notify (/Users/hanfeisun/Workspace/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)
    at promise.Promise.notify_ (/Users/hanfeisun/Workspace/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)
    at Array.forEach (native)
    at promise.Promise.notifyAll_ (/Users/hanfeisun/Workspace/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)
    at goog.async.run.processWorkQueue (/Users/hanfeisun/Workspace/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)
    at runMicrotasksCallback (node.js:337:7)
    at process._tickCallback (node.js:355:11)
>> /Users/hanfeisun/Workspace/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/nexttick.js:41
>>   goog.global.setTimeout(function() { throw exception; }, 0);
>>                                             ^
>> Error: Server terminated early with status 1
>>     at Error (native)
>>     at /Users/hanfeisun/Workspace/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/remote/index.js:204:25
>>     at promise.ControlFlow.runInFrame_ (/Users/hanfeisun/Workspace/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
>>     at goog.defineClass.notify (/Users/hanfeisun/Workspace/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)
>>     at promise.Promise.notify_ (/Users/hanfeisun/Workspace/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)
>>     at Array.forEach (native)
>>     at promise.Promise.notifyAll_ (/Users/hanfeisun/Workspace/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)
>>     at goog.async.run.processWorkQueue (/Users/hanfeisun/Workspace/videojs-contrib-hls/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)
>>     at runMicrotasksCallback (node.js:337:7)
>>     at process._tickCallback (node.js:355:11)
Warning: Tests failed, protractor exited with code: 1 Use --force to continue.

Aborted due to warnings.
```

I tried `npm cache clean && rm -rf ./node_modules && git clean -f -d`, but it doens't work..

**Comment by hanfeisun** [comment]
It is solved. The reason is that the Java version in Mac OSX El Capitan is 1.6, while selenium need 1.7. After I installed jdk 1.7 from oracle, it works well now
