### ISSUE TITLE
How to append playlist dynamically (HLS VoD)?

### ISSUE THREAD

**Issue by mikeevstropov** [videojs/videojs-contrib-hls#602]
Hi!
I try to append source dynamically, but i see on console:
``` console
VIDEOJS: TypeError: Cannot read property 'length' of undefined
    at e.o.value (http://myhost.com/js/videojs-contrib-hls.min.js:10:30981)
    at e.o.value (http://myhost.com/js/videojs-contrib-hls.min.js:10:30557)
    at e.o.value (http://myhost.com/js/videojs-contrib-hls.min.js:10:30716)
    at new e (http://myhost.com/js/videojs-contrib-hls.min.js:10:24239)
    at Object.N.handleSource (http://myhost.com/js/videojs-contrib-hls.min.js:11:5145)
    at b.a.setSource (http://myhost.com/js/video.min.js:20:6396)
    at b.techCall_ (http://myhost.com/js/video.min.js:16:27476)
    at b.<anonymous> (http://myhost.com/js/video.min.js:17:551)
    at b.a.ready (http://myhost.com/js/video.min.js:14:6318)
    at b.src (http://myhost.com/js/video.min.js:17:489)
```
My html:
``` html
<link href="/css/video-js.min.css" rel="stylesheet">
<script src="/js/video.min.js"></script>
<script src="/js/videojs-contrib-hls.min.js"></script>
<div id='player'></div>
```
My javascript:
``` javascript
player = videojs('player', {});
player.src({
    type : "application/x-mpegURL",
    src  : 'http://mydomain/master.m3u8'
});
```
My master playlist:
``` console
#EXTM3U
#EXT-X-STREAM-INF:RESOLUTION=640x272,BANDWIDTH=372000
http://myhost.com/source1.m3u8
#EXT-X-STREAM-INF:RESOLUTION=1128x480,BANDWIDTH=566000
http://myhost.com/source2.m3u8
#EXT-X-STREAM-INF:RESOLUTION=1280x544,BANDWIDTH=1034000
http://myhost.com/source3.m3u8
```
Playlist is correctly, it works with other hls player, but not working on videojs.
Why latest videojs with contrib-hls not playing on any browsers?
Thank you!

**Comment by dmlap** [comment]
Would you mind putting together a minimal example we could take a look at?

**Comment by mikeevstropov** [comment]
@dmlap Hi! This is my example:
http://warnerfilm.ru/moonplayer/serial/dd9db3509c39f5dbce14bc21795928b8/iframe
