### ISSUE TITLE
no such file or directory '/var/www/node_modules/videojs-contrib-hls/utils/manifest'

### ISSUE THREAD

**Issue by FDiskas** [videojs/videojs-contrib-hls#807]
Trying to build from source
```
> videojs-contrib-hls@3.4.0 build:js:babel /var/www/node_modules/videojs-contrib-hls
> babel src -d es5


fs.js:659
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/var/www/node_modules/videojs-contrib-hls/utils/manifest'
    at Object.fs.readdirSync (fs.js:659:18)
    at Object.build (/var/www/node_modules/videojs-contrib-hls/scripts/manifest-data.js:14:18)
    at [eval]:1:48
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:532:25)
    at startup (node.js:80:7)
    at node.js:902:3
```

**Comment by BrandonOCasey** [comment]
HLS on npm does not contain all of the files needed to build it, and I think that is why you are seeing the error. You can checkout a release tag from the git repository (probably the preferred way) and then run `npm link <videojs-contrib-hls_cloned_git_dir>` in the project that you are trying to use it in. If you need any more info on this feel free to re-open this issue!
