### ISSUE TITLE
Closed captions playback issue: Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by askaliuk** [videojs/videojs-contrib-hls#892]
## Description
`video-contrib-hls` raises an exception during HLS stream playback with closed captions.

## Sources
http://playertest.longtailvideo.com/adaptive/captions/playlist.m3u8

## Steps to reproduce
Open following URL:
http://www.w3schools.com/code/tryit.asp?filename=F0EFFPUMR91Z

1. Start playback, click CC button and enable closed captions by clicking on `cc1` track
2. Wait for 1-3 seconds and disable closed captions by clicking on `captions off`
3. Open browser console and let playback go. Around 1:15-1:30 browser will raise an exception.

### Error output
```
videojs-contrib-hls.js:14349 Uncaught TypeError: Cannot read property 'length' of null
    at removeCuesFromTrack (https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/3.6.6/videojs-contrib-hls.js:14349:17)
    at VirtualSourceBuffer.remove (https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/3.6.6/videojs-contrib-hls.js:15121:44)
    at SourceUpdater.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/3.6.6/videojs-contrib-hls.js:4314:30)
    at SourceUpdater.runCallback_ (https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/3.6.6/videojs-contrib-hls.js:4369:21)
    at SourceUpdater.queueCallback_ (https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/3.6.6/videojs-contrib-hls.js:4355:12)
    at SourceUpdater.remove (https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/3.6.6/videojs-contrib-hls.js:4313:12)
    at SegmentLoader.loadSegment_ (https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/3.6.6/videojs-contrib-hls.js:3757:29)
    at SegmentLoader.fillBuffer_ (https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/3.6.6/videojs-contrib-hls.js:3686:12)
    at SegmentLoader.monitorBuffer_ (https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/3.6.6/videojs-contrib-hls.js:3489:14)
```

### Additional information
Bug is probably here:
https://github.com/videojs/videojs-contrib-media-sources/blob/v4.0.4/src/remove-cues-from-track.js#L21

`track.cues` can be null

### videojs-contrib-hls version
videojs-contrib-hls 3.6.6

### videojs version
video.js 5.11.9

### Browsers
Chrome 54.0.2840.71, but I'm pretty sure the bug can be repeated in any browser

### Platforms
I tested on OSX, but I'm pretty sure a bug can be repeated in any platform

**Comment by askaliuk** [comment]
Looks like it was fixed in https://github.com/videojs/videojs-contrib-media-sources/pull/113

**Comment by dmlap** [comment]
@askaliuk thanks for noting that fixed the issue. Closing.

**Comment by askaliuk** [comment]
@dmlap thank you. May I ask when this change will go into `video.js.hls` release?
I saw this commit:
https://github.com/videojs/videojs-contrib-hls/commit/2165f9dc0090449fa8106fcf361730df001af528

But `videojs-contrib-media-sources` was not updated.

**Comment by dmlap** [comment]
@askaliuk the `^` operator in the version should pick up the latest patch version of contrib-media-sources so it's only necessary to rebuild and re-tag to pick up the change. I definitely agree it's a bit confusing.

**Comment by askaliuk** [comment]
@dmlap just tested. Unfortunately your commit does not fix the issue.

**Comment by anaszgh** [comment]
Hello, 

I'm facing the same issue on Video-Js version 7.0.2, how can i fix it.
